name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:

    runs-on: ec2-user

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/event_demo/public_html

            git pull origin main

            npm install

            pm2 restart eventadmin
